# Generated by Django 4.1.5 on 2024-10-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Candidate', '0001_initial'),
        ('PoliticalParty', '0001_initial'),
        ('Constituency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyElectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=10, null=True, unique=True)),
                ('state_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Constituency.statemodel')),
            ],
            options={
                'verbose_name': 'Assembly Election',
                'verbose_name_plural': 'Assembly Elections',
            },
        ),
        migrations.CreateModel(
            name='AssemblyElectionToAllianceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PoliticalParty.alliancemodel')),
                ('assembly_election_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssemblyElections.assemblyelectionmodel')),
            ],
            options={
                'verbose_name': 'Assembly Election To Alliance',
                'verbose_name_plural': 'Assembly Election To Alliance',
                'unique_together': {('assembly_election_id', 'alliance_id')},
            },
        ),
        migrations.CreateModel(
            name='AssemblyElectionToAssemblyConstituencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('GEN', 'General'), ('SC', 'Schedule Cast'), ('ST', 'Schedule Tribe')], max_length=10, null=True)),
                ('electors', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('date_of_poll', models.DateField(blank=True, null=True)),
                ('date_of_result', models.DateField(blank=True, null=True)),
                ('assembly_constituency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Constituency.assemblyconstituencymodel')),
                ('assembly_election_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssemblyElections.assemblyelectionmodel')),
            ],
            options={
                'verbose_name': 'Assembly Election To Assembly Constituency',
                'verbose_name_plural': 'Assembly Election To Assembly Constituencies',
                'unique_together': {('assembly_election_id', 'assembly_constituency_id')},
            },
        ),
        migrations.CreateModel(
            name='AssemblyElectionToAssemblyConstituencyToCandidateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('assembly_election_to_assembly_constituency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssemblyElections.assemblyelectiontoassemblyconstituencymodel')),
                ('candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Candidate.candidatemodel')),
                ('political_party_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PoliticalParty.politicalpartymodel')),
            ],
            options={
                'verbose_name': 'Assembly Election To Assembly Constituency To Candidate',
                'verbose_name_plural': 'Assembly Election To Assembly Constituency To Candidates',
                'unique_together': {('assembly_election_to_assembly_constituency_id', 'candidate_id', 'political_party_id')},
            },
        ),
        migrations.CreateModel(
            name='AssemblyElectionToAllianceToPoliticalPartyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_election_to_alliance_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssemblyElections.assemblyelectiontoalliancemodel')),
                ('political_party_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PoliticalParty.politicalpartymodel')),
            ],
            options={
                'verbose_name': 'Assembly Election To Alliance To Political Party',
                'verbose_name_plural': 'Assembly Election To Alliance To Political Parties',
                'unique_together': {('assembly_election_to_alliance_id', 'political_party_id')},
            },
        ),
    ]
